1748243671387	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=schedule)
1748243711654	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1748243711654	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1748243711656	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=schedule)
1748243711658	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1748243711661	Sync.SyncScheduler	DEBUG	Woke from sleep.
1748243711662	Sync.SyncScheduler	DEBUG	Online, will sync in 2s.
1748243711662	Sync.SyncScheduler	DEBUG	Next sync in 2000 ms. (why=wake_notification)
1748243711663	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1748243713749	Sync.Service	DEBUG	User-Agent: Firefox/138.0.4 (Linux x86_64) FxSync/1.140.0.20250518015817.desktop
1748243713749	Sync.Service	INFO	Starting sync at 2025-05-26 12:45:13 in browser session Vi5FfQU6OY1Y
1748243713749	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1748243713752	Sync.Status	INFO	Resetting Status.
1748243713752	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1748243713752	FirefoxAccounts	TRACE	not checking freshness of profile as it remains recent
1748243713754	Sync.Resource	WARN	GET request to https://sync-1-us-west1-g.sync.services.mozilla.com/1.5/195504406/info/collections failed: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1748243713754	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1748243713754	Sync.Status	DEBUG	Status.service: success.status_ok => error.sync.failed
1748243713754	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1748243713754	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=reschedule)
1748243713756	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
