1748210442428	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=schedule)
1748210664782	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1748210664783	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1748210664784	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1748210664787	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1748210664790	Sync.SyncScheduler	DEBUG	Woke from sleep.
1748210664791	Sync.SyncScheduler	DEBUG	Online, will sync in 2s.
1748210664791	Sync.SyncScheduler	DEBUG	Next sync in 2000 ms. (why=wake_notification)
1748210664794	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1748210666796	Sync.Service	DEBUG	User-Agent: Firefox/138.0.4 (Linux x86_64) FxSync/1.140.0.20250518015817.desktop
1748210666796	Sync.Service	INFO	Starting sync at 2025-05-26 03:34:26 in browser session ijTfEytkQJsp
1748210666796	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1748210666802	Sync.Status	INFO	Resetting Status.
1748210666802	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1748210666803	FirefoxAccounts	DEBUG	FxAccountsProfileClient: Requested profile
1748210666803	FirefoxAccounts	DEBUG	getOAuthToken enter
1748210666804	FirefoxAccounts	TRACE	getCachedToken returning cached token
1748210666804	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1748210666804	Services.Common.RESTRequest	DEBUG	GET request to https://profile.accounts.firefox.com/v1/profile
1748210666811	Services.Common.RESTRequest	DEBUG	GET https://profile.accounts.firefox.com/v1/profile failed: 2152398878 - NS_ERROR_UNKNOWN_HOST
1748210666812	FirefoxAccounts	ERROR	Background refresh of profile failed: {"name":"FxAccountsProfileClientError","code":null,"errno":998,"error":"NETWORK_ERROR","message":"[Exception... \"NS_ERROR_UNKNOWN_HOST\"  nsresult: \"0x804b001e (NS_ERROR_UNKNOWN_HOST)\"  location: \"JS frame :: resource://services-common/rest.sys.mjs :: onStopRequest :: line 478\"  data: no]"}
1748210666813	Sync.Resource	WARN	GET request to https://sync-1-us-west1-g.sync.services.mozilla.com/1.5/195504406/info/collections failed: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1748210666813	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1748210666813	Sync.Status	DEBUG	Status.service: success.status_ok => error.sync.failed
1748210666813	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1748210666814	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=reschedule)
1748210666817	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
