1748000241127	Sync.LogManager	DEBUG	Flushing file log
1748000241128	Sync.LogManager	DEBUG	Log cleanup threshold time: 1747136241128
1748000241129	Sync.LogManager	DEBUG	Done deleting files.
1748000313850	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1748000313850	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1748000313851	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=schedule)
1748000313854	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1748000324497	Sync.SyncScheduler	DEBUG	Network link status changed to "up". Offline?: false
1748000324498	Sync.SyncScheduler	DEBUG	Network link looks up. Syncing.
1748000324500	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1748000324501	Sync.Service	DEBUG	User-Agent: Firefox/138.0.4 (Linux x86_64) FxSync/1.140.0.20250518015817.desktop
1748000324501	Sync.Service	INFO	Starting sync at 2025-05-23 17:08:44 in browser session wt9PXLXT_ZJY
1748000324501	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1748000324503	Sync.Status	INFO	Resetting Status.
1748000324503	Sync.Status	DEBUG	Status.service: error.sync.failed => success.status_ok
1748000324504	FirefoxAccounts	DEBUG	FxAccountsProfileClient: Requested profile
1748000324504	FirefoxAccounts	DEBUG	getOAuthToken enter
1748000324504	FirefoxAccounts	TRACE	getCachedToken returning cached token
1748000324504	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1748000324504	Services.Common.RESTRequest	DEBUG	GET request to https://profile.accounts.firefox.com/v1/profile
1748000334844	Services.Common.RESTRequest	DEBUG	GET https://profile.accounts.firefox.com/v1/profile failed: 2152398878 - NS_ERROR_UNKNOWN_HOST
1748000334844	FirefoxAccounts	ERROR	Background refresh of profile failed: {"name":"FxAccountsProfileClientError","code":null,"errno":998,"error":"NETWORK_ERROR","message":"[Exception... \"NS_ERROR_UNKNOWN_HOST\"  nsresult: \"0x804b001e (NS_ERROR_UNKNOWN_HOST)\"  location: \"JS frame :: resource://services-common/rest.sys.mjs :: onStopRequest :: line 478\"  data: no]"}
1748000334845	Sync.Resource	WARN	GET request to https://sync-1-us-west1-g.sync.services.mozilla.com/1.5/195504406/info/collections failed: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1748000334845	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1748000334845	Sync.Status	DEBUG	Status.service: success.status_ok => error.sync.failed
1748000334845	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1748000334845	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=reschedule)
1748000334848	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
