1748297519938	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=schedule)
1748298133093	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1748298133094	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1748298133095	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1748298133098	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1748298133101	Sync.SyncScheduler	DEBUG	Woke from sleep.
1748298133103	Sync.SyncScheduler	DEBUG	Online, will sync in 2s.
1748298133104	Sync.SyncScheduler	DEBUG	Next sync in 2000 ms. (why=wake_notification)
1748298133105	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1748298135111	Sync.Service	DEBUG	User-Agent: Firefox/138.0.4 (Linux x86_64) FxSync/1.140.0.20250518015817.desktop
1748298135111	Sync.Service	INFO	Starting sync at 2025-05-27 03:52:15 in browser session wqB4joW0o9fN
1748298135112	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1748298135114	Sync.Status	INFO	Resetting Status.
1748298135114	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1748298135115	FirefoxAccounts	DEBUG	FxAccountsProfileClient: Requested profile
1748298135115	FirefoxAccounts	DEBUG	getOAuthToken enter
1748298135115	FirefoxAccounts	TRACE	getCachedToken returning cached token
1748298135115	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1748298135116	Services.Common.RESTRequest	DEBUG	GET request to https://profile.accounts.firefox.com/v1/profile
1748298135118	Services.Common.RESTRequest	DEBUG	GET https://profile.accounts.firefox.com/v1/profile failed: 2152398878 - NS_ERROR_UNKNOWN_HOST
1748298135118	FirefoxAccounts	ERROR	Background refresh of profile failed: {"name":"FxAccountsProfileClientError","code":null,"errno":998,"error":"NETWORK_ERROR","message":"[Exception... \"NS_ERROR_UNKNOWN_HOST\"  nsresult: \"0x804b001e (NS_ERROR_UNKNOWN_HOST)\"  location: \"JS frame :: resource://services-common/rest.sys.mjs :: onStopRequest :: line 478\"  data: no]"}
1748298135119	Sync.Resource	WARN	GET request to https://sync-1-us-west1-g.sync.services.mozilla.com/1.5/195504406/info/collections failed: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1748298135119	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1748298135119	Sync.Status	DEBUG	Status.service: success.status_ok => error.sync.failed
1748298135119	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1748298135119	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=reschedule)
1748298135121	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
