1747909729919	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1747910044587	Sync.SyncScheduler	DEBUG	Woke from sleep.
1747910044588	Sync.SyncScheduler	DEBUG	Online, will sync in 2s.
1747910044588	Sync.SyncScheduler	DEBUG	Next sync in 2000 ms. (why=wake_notification)
1747910044588	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1747910044592	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1747910044592	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1747910044596	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1747910044599	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1747910049190	Sync.Service	DEBUG	User-Agent: Firefox/138.0.4 (Linux x86_64) FxSync/1.140.0.20250518015817.desktop
1747910049190	Sync.Service	INFO	Starting sync at 2025-05-22 16:04:09 in browser session 9LzWDoqYy_HG
1747910049190	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1747910049192	Sync.Status	INFO	Resetting Status.
1747910049192	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1747910049193	FirefoxAccounts	DEBUG	FxAccountsProfileClient: Requested profile
1747910049193	FirefoxAccounts	DEBUG	getOAuthToken enter
1747910049193	FirefoxAccounts	TRACE	getCachedToken returning cached token
1747910049193	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1747910049193	Services.Common.RESTRequest	DEBUG	GET request to https://profile.accounts.firefox.com/v1/profile
1747910049194	Sync.SyncAuthManager	INFO	Getting sync key
1747910049194	FirefoxAccounts	DEBUG	getOAuthToken enter
1747910049194	FirefoxAccounts	TRACE	getCachedToken returning cached token
1747910049194	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1747910049194	Sync.SyncAuthManager	INFO	Getting a sync token from: https://token.services.mozilla.com/1.0/sync/1.5
1747910049194	Sync.SyncAuthManager	DEBUG	Getting a token using OAuth
1747910049194	Services.Common.TokenServerClient	DEBUG	Beginning OAuth token exchange: https://token.services.mozilla.com/1.0/sync/1.5
1747910049194	Services.Common.RESTRequest	DEBUG	GET request to https://token.services.mozilla.com/1.0/sync/1.5
1747910049195	Services.Common.RESTRequest	DEBUG	GET https://profile.accounts.firefox.com/v1/profile failed: 2152398878 - NS_ERROR_UNKNOWN_HOST
1747910049195	FirefoxAccounts	ERROR	Background refresh of profile failed: {"name":"FxAccountsProfileClientError","code":null,"errno":998,"error":"NETWORK_ERROR","message":"[Exception... \"NS_ERROR_UNKNOWN_HOST\"  nsresult: \"0x804b001e (NS_ERROR_UNKNOWN_HOST)\"  location: \"JS frame :: resource://services-common/rest.sys.mjs :: onStopRequest :: line 478\"  data: no]"}
1747910049195	Services.Common.RESTRequest	DEBUG	GET https://token.services.mozilla.com/1.0/sync/1.5 failed: 2152398878 - NS_ERROR_UNKNOWN_HOST
1747910049195	Sync.SyncAuthManager	ERROR	Non-authentication error in _fetchTokenForUser: TokenServerClientNetworkError({"error":{}})(resource://services-common/tokenserverclient.sys.mjs:28:36) JS Stack trace: TokenServerClientNetworkError@tokenserverclient.sys.mjs:51:16
_tokenServerExchangeRequest@tokenserverclient.sys.mjs:235:13
1747910049195	Sync.Status	DEBUG	Status.login: success.login => error.login.reason.network
1747910049195	Sync.Status	DEBUG	Status.service: success.status_ok => error.login.failed
1747910049195	FirefoxAccounts	TRACE	Getting command keys: https://identity.mozilla.com/cmd/open-uri
1747910049195	Sync.SyncAuthManager	ERROR	Failed to fetch a token for authentication: TokenServerClientNetworkError({"error":{}})(resource://services-common/tokenserverclient.sys.mjs:28:36) JS Stack trace: TokenServerClientNetworkError@tokenserverclient.sys.mjs:51:16
_tokenServerExchangeRequest@tokenserverclient.sys.mjs:235:13
1747910049196	FirefoxAccounts	TRACE	not checking freshness of profile as it remains recent
1747910049196	FirefoxAccounts	TRACE	Getting command keys: https://identity.mozilla.com/cmd/close-uri/v1
1747910049197	Sync.Resource	WARN	GET request to https://sync-1-us-west1-g.sync.services.mozilla.com/1.5/195504406/info/collections failed: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1747910049197	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1747910049198	Sync.Status	DEBUG	Status.service: error.login.failed => error.sync.failed
1747910049198	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1747910049198	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=reschedule)
1747910049198	Sync.Telemetry	INFO	Early submission of sync telemetry due to changed IDs/NodeType
1747910049203	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
